# Generated by Django 5.1.2 on 2024-11-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.TextField(default='green'),
        ),
    ]
