# Generated by Django 5.1.2 on 2024-11-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='color',
        ),
    ]
